#ifndef MAIL_HEADER

	//Constants
	#define DEFAULT_SMTP_PORT 25

	//properties
	#define SMTP_SERVER_LOCATION_PROPERTY "SMTP_SERVER_LOCATION"
	#define SMTP_SERVER_PASSWORD_PROPERTY "SMTP_SERVER_PASSWORD"
	#define SMTP_SERVER_USERNAME_PROPERTY "SMTP_SERVER_USERNAME"
	#define SMTP_SERVER_PORT_PROPERTY "SMTP_SERVER_PORT"
	#define SMTP_FROM_PROPERTY "SMTP_FROM_ADDRESS"
	#define SMTP_TO_PROPERTY "SMTP_TO_ADDRESSES"
	
	//Functions
	export prototype INT ValidateMailServerSettings(HWND);


#endif
#define MAIL_HEADER
