#!/bin/sh

# Generate the destiny RPM package from the build  

if [ ! -n "$BJROOT" ] ; then
    echo "\$BJROOT is not defined.  Please set env variable \$BJROOT";
    exit;
fi

if [ $# -eq 1 ] ; then
    template=$1;
else
    echo "Usage: $0 templatefile";
    echo "   e.g. $0 agent.rpm-spec.template"
    exit;
fi


# Step 1. Gen the directory tree for RPM to work
# No need for other rpm directories

dirlist=( rpm rpm/BUILD rpm/RPMS rpm/RPMS/i386 )

for d in "${dirlist[@]}" ; do 
    if [ ! -d ${BJROOT}/$d ] ; then
        mkdir -p ${BJROOT}/$d;
    fi
done

# Step 2. Gen the macro file to tell RPM to use personal directory
echo "%_topdir ${BJROOT}/rpm" > ${HOME}/.rpmmacros

# Step 3. Gen the spec file for RPM to work on

rm -f /tmp/$$.spec;

date=`date +%y%m%d`;
userid=`whoami`;
fullname=`finger $userid@localhost | grep Name | sed "s/^.*Name://"`;
email=`echo $fullname | tr ' ' '.'`;

cat $template | \
while read line
    do 
        line=`echo $line | sed "s/___DATE___/${date}/"`;
        line=`echo $line | sed "s/___NAME___/${fullname}/"`;
        line=`echo $line | sed "s/___EMAIL___/${email}/"`;
        line=`echo $line | sed "s|___BJROOT___|${BJROOT}|"`;
        echo $line >> /tmp/$$.spec;
    done

# Step 4 Gen the RPM package
rpmbuild -bb /tmp/$$.spec ; 

# cleanup
rm -f /tmp/$$.spec ;
