#
# Cookbook Name:: ControlCenter
# library:: config_tokens.rb
#     all configuration tokens listed here
#
#
# Copyright 2015, Nextlabs Inc.
# Author:: Amila Silva
#
# All rights reserved - Do Not Redistribute
#

module ConfigTokens

  AUTHENTICATION_MODE_TOKEN = '[AUTH_MODE]'

  EXTERNAL_DOMAIN_BEGIN_TOKEN = '<!--[EXTERNAL_DOMAIN_SWITCH_BEGIN]-->'
  EXTERNAL_DOMAIN_END_TOKEN = '<!--[EXTERNAL_DOMAIN_SWITCH_END]-->'
  EXTERNAL_DOMAIN_BEGIN_COMMENT_TOKEN = '<!--[EXTERNAL_DOMAIN_SWITCH_BEGIN] '
  EXTERNAL_DOMAIN_END_COMMENT_TOKEN = ' [EXTERNAL_DOMAIN_SWITCH_END]-->'

  DEFAULT_EMAIL_HANDLER_BEGIN_TOKEN = '<!--[DEFAULT_EMAIL_HANDLER_BEGIN]-->'
  DEFAULT_EMAIL_HANDLER_END_TOKEN = '<!--[DEFAULT_EMAIL_HANDLER_END]-->'
  DEFAULT_EMAIL_HANDLER_BEGIN_COMMENT_TOKEN = '<!--[DEFAULT_EMAIL_HANDLER_BEGIN] '
  DEFAULT_EMAIL_HANDLER_END_COMMENT_TOKEN = ' [DEFAULT_EMAIL_HANDLER_END]-->'
  SMTP_SERVER_HOST_TOKEN = '[SMTP_SERVER_HOST]'
  SMTP_SERVER_PASSWORD_TOKEN = '[SMTP_SERVER_PASSWORD]'
  SMTP_SERVER_PORT_TOKEN = '[SMTP_SERVER_PORT]'
  SMTP_SERVER_USERNAME_TOKEN = '[SMTP_SERVER_USERNAME]'
  SMTP_FROM_ADDRESS_TOKEN = '[SMTP_FROM_ADDRESS]'
  SMTP_TO_ADDRESSES_TOKEN = '[SMTP_TO_ADDRESSES]'

  ACTIVITY_DATABASE_CONNECT_TOKEN = '[ACTIVITY_DATABASE_CONNECTSTRING]'
  ACTIVITY_DATABASE_DIALECT_TOKEN = '[ACTIVITY_DATABASE_DIALECT]'
  ACTIVITY_DATABASE_DRIVER_TOKEN = '[ACTIVITY_DATABASE_DRIVER]'
  ACTIVITY_DATABASE_PASSWORD_TOKEN = '[ACTIVITY_DATABASE_PASSWORD]'
  ACTIVITY_DATABASE_USERNAME_TOKEN  = '[ACTIVITY_DATABASE_USERNAME]'

  MGMT_DATABASE_CONNECT_TOKEN = '[MGMT_DATABASE_CONNECTSTRING]'
  MGMT_DATABASE_DIALECT_TOKEN = '[MGMT_DATABASE_DIALECT]'
  MGMT_DATABASE_DRIVER_TOKEN = '[MGMT_DATABASE_DRIVER]'
  MGMT_DATABASE_PASSWORD_TOKEN = '[MGMT_DATABASE_PASSWORD]'
  MGMT_DATABASE_USERNAME_TOKEN = '[MGMT_DATABASE_USERNAME]'

  DICT_DATABASE_CONNECT_TOKEN = '[DICT_DATABASE_CONNECTSTRING]'
  DICT_DATABASE_DIALECT_TOKEN = '[DICT_DATABASE_DIALECT]'
  DICT_DATABASE_DRIVER_TOKEN = '[DICT_DATABASE_DRIVER]'
  DICT_DATABASE_PASSWORD_TOKEN = '[DICT_DATABASE_PASSWORD]'
  DICT_DATABASE_USERNAME_TOKEN = '[DICT_DATABASE_USERNAME]'

  PF_DATABASE_CONNECT_TOKEN = '[PF_DATABASE_CONNECTSTRING]'
  PF_DATABASE_DIALECT_TOKEN = '[PF_DATABASE_DIALECT]'
  PF_DATABASE_DRIVER_TOKEN = '[PF_DATABASE_DRIVER]'
  PF_DATABASE_PASSWORD_TOKEN = '[PF_DATABASE_PASSWORD]'
  PF_DATABASE_USERNAME_TOKEN = '[PF_DATABASE_USERNAME]'

  #  EMBEDDED_DB_USERNAME_TOKEN = '[REPOSITORY_USERNAME]'
  #  EMBEDDED_DB_PASSWORD_TOKEN = '[REPOSITORY_PASSWORD]'
  #  EMBEDDED_DB_SERVICE_USERNAME_TOKEN = '[EMBEDDED_DB_SERVICE_USERNAME]'
  #  EMBEDDED_DB_SERVICE_PASSWORD_TOKEN = '[EMBEDDED_DB_SERVICE_PASSWORD]'
  #  EMBEDDED_DB_HOST_TOKEN = '[REPOSITORY_DBSERVER]'
  #  EMBEDDED_DB_PORT_TOKEN = '[REPOSITORY_DBPORT]'

  WINDOWS_AUTH_DOMAIN_CONTROLLER_TOKEN = '[DOMAIN_CONTROLLER]'
  WINDOWS_AUTH_DOMAIN_CONTROLLER_PORT_TOKEN = '[DOMAIN_CONTROLLER_DIRECTORY_PORT]'
  WINDOWS_AUTH_DOMAIN_NAME_TOKEN = '[DOMAIN_NAME]'
  WINDOWS_AUTH_ROOT_DN_TOKEN = '[WINDOWS_USERS_ROOT_DN]'
  WINDOWS_AUTH_LOGIN_DN_TOKEN = '[WINDOWS_USERS_LOGIN_DN]'
  WINDOWS_AUTH_PASSWORD_TOKEN = '[WINDOWS_USERS_PASSWORD]'

  # Key Management
  KM_DATABASE_CONNECT_TOKEN = '[KM_DATABASE_CONNECTSTRING]'
  KM_DATABASE_DIALECT_TOKEN = '[KM_DATABASE_DIALECT]'
  KM_DATABASE_DRIVER_TOKEN = '[KM_DATABASE_DRIVER]'
  KM_DATABASE_PASSWORD_TOKEN = '[KM_DATABASE_PASSWORD]'
  KM_DATABASE_USERNAME_TOKEN = '[KM_DATABASE_USERNAME]'
  KM_KEY_STORE_PASSWORD_TOKEN = '[KM_KEYSTORE_PASSWORD]'

  DMS_BEGIN_TOKEN = '<!--[DMS_COMPONENT_BEGIN]-->'
  DMS_END_TOKEN = '<!--[DMS_COMPONENT_END]-->'
  DMS_BEGIN_COMMENT_TOKEN = '<!--[DMS_COMPONENT_BEGIN] '
  DMS_END_COMMENT_TOKEN = ' [DMS_COMPONENT_END]-->'

  DCSF_BEGIN_TOKEN = '<!--[DCSF_COMPONENT_BEGIN]-->'
  DCSF_END_TOKEN = '<!--[DCSF_COMPONENT_END]-->'
  DCSF_BEGIN_COMMENT_TOKEN = '<!--[DCSF_COMPONENT_BEGIN] '
  DCSF_END_COMMENT_TOKEN = ' [DCSF_COMPONENT_END]-->'

  DABS_BEGIN_TOKEN = '<!--[DABS_COMPONENT_BEGIN]-->'
  DABS_END_TOKEN = '<!--[DABS_COMPONENT_END]-->'
  DABS_BEGIN_COMMENT_TOKEN = '<!--[DABS_COMPONENT_BEGIN] '
  DABS_END_COMMENT_TOKEN = ' [DABS_COMPONENT_END]-->'

  DAC_BEGIN_TOKEN = '<!--[DAC_COMPONENT_BEGIN]-->'
  DAC_END_TOKEN = '<!--[DAC_COMPONENT_END]-->'
  DAC_BEGIN_COMMENT_TOKEN = '<!--[DAC_COMPONENT_BEGIN] '
  DAC_END_COMMENT_TOKEN = ' [DAC_COMPONENT_END]-->'

  DEM_BEGIN_TOKEN = '<!--[DEM_COMPONENT_BEGIN]-->'
  DEM_END_TOKEN = '<!--[DEM_COMPONENT_END]-->'
  DEM_BEGIN_COMMENT_TOKEN = '<!--[DEM_COMPONENT_BEGIN] '
  DEM_END_COMMENT_TOKEN = ' [DEM_COMPONENT_END]-->'

  DPS_BEGIN_TOKEN = '<!--[DPS_COMPONENT_BEGIN]-->'
  DPS_END_TOKEN = '<!--[DPS_COMPONENT_END]-->'
  DPS_BEGIN_COMMENT_TOKEN = '<!--[DPS_COMPONENT_BEGIN] '
  DPS_END_COMMENT_TOKEN = ' [DPS_COMPONENT_END]-->'

  DKMS_BEGIN_TOKEN = '<!--[DKMS_COMPONENT_BEGIN]-->'
  DKMS_END_TOKEN = '<!--[DKMS_COMPONENT_END]-->'
  DKMS_BEGIN_COMMENT_TOKEN = '<!--[DKMS_COMPONENT_BEGIN] '
  DKMS_END_COMMENT_TOKEN = ' [DKMS_COMPONENT_END]-->'

  DDAC_BEGIN_TOKEN = '<!--[DDAC_COMPONENT_BEGIN]-->'
  DDAC_END_TOKEN = '<!--[DDAC_COMPONENT_END]-->'
  DDAC_BEGIN_COMMENT_TOKEN = '<!--[DDAC_COMPONENT_BEGIN] '
  DDAC_END_COMMENT_TOKEN = ' [DDAC_COMPONENT_END]-->'

  ADMIN_BEGIN_TOKEN = '<!--[ADMIN_COMPONENT_BEGIN]-->'
  ADMIN_END_TOKEN = '<!--[ADMIN_COMPONENT_END]-->'
  ADMIN_BEGIN_COMMENT_TOKEN = '<!--[ADMIN_COMPONENT_BEGIN] '
  ADMIN_END_COMMENT_TOKEN = ' [ADMIN_COMPONENT_END]-->'

  REPORTER_BEGIN_TOKEN = '<!--[REPORTER_COMPONENT_BEGIN]-->'
  REPORTER_END_TOKEN = '<!--[REPORTER_COMPONENT_END]-->'
  REPORTER_BEGIN_COMMENT_TOKEN = '<!--[REPORTER_COMPONENT_BEGIN] '
  REPORTER_END_COMMENT_TOKEN = ' [REPORTER_COMPONENT_END]-->'

  CONSOLE_BEGIN_TOKEN = '<!--[CC_CONSOLE_BEGIN]-->'
  CONSOLE_END_TOKEN = '<!--[CC_CONSOLE_END]-->'
  CONSOLE_BEGIN_COMMENT_TOKEN = '<!--[CC_CONSOLE_BEGIN] '
  CONSOLE_END_COMMENT_TOKEN = ' [CC_CONSOLE_END]-->'

  CAS_BEGIN_TOKEN = '<!--[CAS_BEGIN]-->'
  CAS_END_TOKEN = '<!--[CAS_END]-->'
  CAS_BEGIN_COMMENT_TOKEN = '<!--[CAS_BEGIN] '
  CAS_END_COMMENT_TOKEN = ' [CAS_END]-->'

  HELP_BEGIN_TOKEN = '<!--[HELP_BEGIN]-->'
  HELP_END_TOKEN = '<!--[HELP_END]-->'
  HELP_BEGIN_COMMENT_TOKEN = '<!--[HELP_BEGIN] '
  HELP_END_COMMENT_TOKEN = ' [HELP_END]-->'

  CONFIG_SERVICE_BEGIN_TOKEN = '<!--[CONFIG_SERVICE_COMPONENT_BEGIN]-->'
  CONFIG_SERVICE_END_TOKEN = '<!--[CONFIG_SERVICE_COMPONENT_END]-->'
  CONFIG_SERVICE_BEGIN_COMMENT_TOKEN = '<!--[CONFIG_SERVICE_COMPONENT_BEGIN] '
  CONFIG_SERVICE_END_COMMENT_TOKEN = ' [CONFIG_SERVICE_COMPONENT_END]-->'

  HOSTNAME_TOKEN = '[HOSTNAME]'
  INTERNAL_PORT_TOKEN = '[INTERNAL_PORT]'
  EXTERNAL_PORT_TOKEN = '[EXTERNAL_PORT]'
  CONFIG_SERVICE_PORT_TOKEN = '[CONFIG_SERVICE_PORT]'
  IMPORT_PASSWORD_TOKEN = '[SECURITY_PASSWORD]'

  MACHINE_NAME_TOKEN = '[MACHINE_NAME]'
  SHUTDOWN_PORT_TOKEN = '[SHUTDOWN_PORT]'
  GENERATED_KEY_STORE_TOKEN = '[GENERATED_KEY_STORE]'
  GENERATED_TRUST_STORE_TOKEN = '[GENERATED_TRUST_STORE]'

  DMS_HOST_TOKEN = '[DMS_HOST]'
  DMS_PORT_TOKEN = '[DMS_PORT]'
  DAC_HOST_TOKEN = '[DAC_MACHINE]'
  DAC_PORT_TOKEN = '[DAC_PORT]'
  
  # DB init cfg file tokens
  ADMIN_PASSWORD_TOKEN = '[ADMINISTRATOR_PASSWORD]'
  BLUEJUNGLE_HOME_TOKEN = '[BLUEJUNGLE_HOME]'
  INSTALLER_PATH_TOKEN = '[INSTALLER_PATH]'
  JVM_MEMORY_TOKEN = '[JVM_MEMORY]'
  
end unless defined?(ConfigTokens) # https://github.com/sethvargo/chefspec/issues/562#issuecomment-74120922
